[package]
name = "raft"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
mc = { version = "0.1.0", path = "../.." }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.45.0"

[[bin]]
name = "raft"
path = "run.rs"
