[package]
name = "mc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
extract-variant = "1.0.0"
futures = "0.3.31"
tokio = { version = "1.44.1", features = ["sync", "macros", "rt"] }
